# Session 2

In [2]:
import torch
print(torch.__version__)

2.9.1+cpu


In [3]:
x = torch.Tensor([1, 2, 3])
x

tensor([1., 2., 3.])

In [5]:
torch.zeros(3) # size/shape
torch.zeros(3,2)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [6]:
torch.ones(3)

tensor([1., 1., 1.])

In [7]:
torch.rand(3)

tensor([0.8325, 0.0638, 0.4221])

In [9]:
x = torch.tensor([[1,2,3], [4,5,6]]) #2D tensor
x.shape

torch.Size([2, 3])

In [11]:
x = x.to(torch.float32)

In [12]:
x.mean(axis=1)

tensor([2., 5.])

In [13]:
import numpy as np
np_arr = np.array([1,2,3])
tensor = torch.from_numpy(np_arr)
tensor

tensor([1, 2, 3])

In [14]:
x = torch.tensor(2.0, requires_grad = True) # track its gradient
y = x ** 2

In [15]:
y.backward()
x.grad

tensor(4.)

In [16]:
import torch.nn as nn 
import torch.optim as optim
from torchvision import datasets, transforms #cv in pytorch, pyaudio/pyvision/etc
from torch.utils.data import DataLoader

In [39]:
transform = transforms.Compose([
    transforms.ToTensor()
])

In [40]:
train_dataset = datasets.MNIST(
    root='./data',
    train=True,
    transform = transform,
    download=True
)

In [41]:
test_dataset = datasets.MNIST(
    root='./data',
    train=False,
    transform = transform,
    download=True
)

In [42]:
train_loader = DataLoader(train_dataset, batch_size = 64, shuffle=True )
test_loader = DataLoader(test_dataset, batch_size=64)

In [43]:
class NeuralNet(nn.Module):
    def __init__(self):
        super().__init__()

        self.fc1 = nn.Linear(28*28, 128)
        self.relu = nn.ReLU()
        self.fc2 = nn.Linear(128, 10)

    def forward(self, x):
        x = x.view(-1, 28*28) #don't care bout first dim, set def => flatten the data
        x = self.fc1(x)
        x = self.relu(x)
        x = self.fc2(x)
        return x

In [44]:
model = NeuralNet()

In [47]:
loss_fn = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters())


In [50]:
for epochs in range(5):
    for images, labels in train_loader:
        output = model(images)
        loss = loss_fn(output, labels)
        optimizer.zero_grad()
        loss.backward() # calc new grad
        optimizer.step() #optimizer edit ur params
    print(f"epoch: {epochs+1} || loss = {loss.item():.4f}")

epoch: 1 || loss = 0.0213
epoch: 2 || loss = 0.0365
epoch: 3 || loss = 0.0756
epoch: 4 || loss = 0.0112
epoch: 5 || loss = 0.0400


In [55]:
correct = 0
total = 0

with torch.no_grad():
    for image, label in test_loader:
        output = model(image)
        _,predict = torch.max(output,1)
        total+= label.size(0)
        correct += (predict)

RuntimeError: The size of tensor a (64) must match the size of tensor b (16) at non-singleton dimension 0

# TF

Note: you may need to restart the kernel to use updated packages.


ERROR: Could not find a version that satisfies the requirement tensorflow (from versions: none)
ERROR: No matching distribution found for tensorflow


In [54]:
%pip install tensorflow
import tensorflow as tf
from tensorflow.keras import layers, models

Note: you may need to restart the kernel to use updated packages.


ERROR: Could not find a version that satisfies the requirement tensorflow (from versions: none)
ERROR: No matching distribution found for tensorflow


ModuleNotFoundError: No module named 'tensorflow'

In [ ]:
(x_train, y_train), (x_test, y_test) = tf.akeras.datasets.mnist.load_data()

In [ ]:
x_train = x_train / 255.0
x_test = x_test / 255.0

In [ ]:
model = models.Sequential([
    layers.Flatten(),
    layers.Dense(128, activation='relu'),
    layers.Dense(128, activation='relu'),
    layers.Dense(10)
])

In [ ]:
loss_fn = tf.keras.losses.SparseCategoricalCrossEntropy(from_logits=True)

optimizer = tf.keras.optimizers.Adam()


In [ ]:
model.compile(optimizer, loss_fn)
model.fit(x_train, y_train)

In [ ]:
output = model.predict(x_test)
pred_idx = tf.argmax(output, axis=1)
tf.keras.metrics.Accuracy(y_test, pred_idx)